name: '[CI/CD] Publish Package to npmjs'
on:
  release:
    types:
      - created
# on:
#   push:
#     tags:
#     - 'v*.*.*'
permissions:
  contents: read
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.FLOMESH_DOCKERHUB_USERNAME }}
        password: ${{ secrets.FLOMESH_DOCKERHUB_PASSWORD }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v4.1.1
      with:
        images: flomesh/readme-generator-for-helm
        tags: |
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=sha,format=short
        flavor: |
          latest=auto

    - name: Build and Push image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
